apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        imagePullPolicy: Always
        image: marktward/grpchw:kube
        ports:
        - containerPort: 8010
          name: client
        command: ["greeter_client"]
