apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeter
        tier: backend
        component: grpc
    spec:
      containers:
      - name: greeter-be
        imagePullPolicy: Always
        image: marktward/grpchw:kube
        ports:
          - name: greeter-be
            containerPort: 8000
        command: ["greeter_server"]
