version: "3"

services:
  # greeter-grpc is used as network alias and must match addressDB value in pkg handlers
  greeter-grpc:
    image: marktward/grpchw:kube
    command: greeter_server
    expose:
      - 8000

  client:
    image: marktward/grpchw:kube
    ports:
      - 8010:8010
    command: greeter_client
